# Generated by Django 2.0.5 on 2018-05-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='Course',
            new_name='course',
        ),
    ]
