# Generated by Django 2.0.5 on 2018-05-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=50, verbose_name='访问地址'),
        ),
    ]
